package es.ramondin.model.bc.views.client;

import es.ramondin.model.bc.views.common.PobladaProgVO;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 01 17:54:32 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PobladaProgVOClient extends ViewUsageImpl implements PobladaProgVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PobladaProgVOClient() {
    }


    public BigDecimal getValorYParaKP(Number valorK, Number valorP) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorYParaKP",new String [] {"java.lang.Number","java.lang.Number"},new Object[] {valorK, valorP});
        return (BigDecimal)_ret;
    }

    public BigDecimal getValorXParaY(BigDecimal valorY) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorXParaY",new String [] {"java.math.BigDecimal"},new Object[] {valorY});
        return (BigDecimal)_ret;
    }


    public BigDecimal getValorYParaX(BigDecimal valorX) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorYParaX",new String [] {"java.math.BigDecimal"},new Object[] {valorX});
        return (BigDecimal)_ret;
    }

    public String getFuncionY() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getFuncionY",null,null);
        return (String)_ret;
    }

    public void obtenerRegresion(String valoresX, String valoresY) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"obtenerRegresion",new String [] {"java.lang.String","java.lang.String"},new Object[] {valoresX, valoresY});
        return;
    }

    public String getValorYParaX(String valorX) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorYParaX",new String [] {"java.lang.String"},new Object[] {valorX});
        return (String)_ret;
    }

    public String getValorYParaKP(String valorK, String valorP) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorYParaKP",new String [] {"java.lang.String","java.lang.String"},new Object[] {valorK, valorP});
        return (String)_ret;
    }

    public String getValorXParaY(String valorY) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorXParaY",new String [] {"java.lang.String"},new Object[] {valorY});
        return (String)_ret;
    }
}
